name: Bandit Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '40 5 * * 5'
  workflow_dispatch:

jobs:
  bandit_scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Perform Bandit Analysis
        uses: PyCQA/bandit-action@v1
        with:
          severity: "all"
          confidence: "all"
