name: Bandit Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '40 5 * * 5'
  workflow_dispatch:

jobs:
  bandit_scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - name: Perform Bandit Analysis
      uses: PyCQA/bandit-action@8a1b30610f61f3f792fe7556e888c9d7dffa52de # v1.0.0
      with:
        severity: "all"
        confidence: "all"
